"""add_category_indexes

Revision ID: c7fe2885a8d0
Revises: c9eef0417120
Create Date: 2026-09-14 08:20:45.716749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7fe2885a8d0'
down_revision: Union[str, Sequence[str], None] = 'c9eef0417120'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_posts_category', 'posts', ['category'], unique=False)
    op.create_index('idx_reels_category', 'reels', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_reels_category', table_name='reels')
    op.drop_index('idx_posts_category', table_name='posts')
    # ### end Alembic commands ###
